### ISSUE TITLE
Proposal: use yaml to define the theme

### ISSUE THREAD

**Issue by Uaitt** [s1e2b3i4/onenord-vscode#4]
Hey @s1e2b3i4 @rmehri01 ,
as you might know, I have recently been working in order to improve this theme. I am here to make a sort of proposal.

The theme here is defined using JSON. However, JSON does not have the concept of "placeholders", thus every color is duplicated on every rule. This not only makes the theme very hard to read (well, it's harder to read something like `#ff0000` than `red`), but also makes it hard to maintain (if we modify one color, all the occurrences of that colour have to be changed accordingly).

I have done a few researches, and in particular my attention was caught by how the [dracula theme](https://github.com/dracula/visual-studio-code) originators defined the theme.

As you see, they first define the theme using a yaml file and leveraging placeholders (in [src/dracula.yml](https://github.com/dracula/visual-studio-code/blob/master/src/dracula.yml)). Then, they (probably??) convert the theme into a JSON (the only format vs-code understand, I guess?) by using some JavaScript (inside of [scripts/](https://github.com/dracula/visual-studio-code/tree/master/scripts)).

I guess it would be cool if we were able to make the same here. This will make the theme very readable and possibly attract more maintainers!

Unfortunately, I have no experience with writing JavaScript, thus I don't think I can help much when it comes to writing the js code that converts the yaml into JSON (well, I could look at the dracula code, but I had some issues understanding what was happening xD). I would however be glad to help in converting the JSON file into a YAML, if somebody was down to help :) 

WDYT?

**Comment by s1e2b3i4** [comment]
Hey, thank you for your idea and research!

I also think that the theme would benefit from a more clear structure via “placeholders”. The way how the dracula theme approaches this problem is very neat, in my opinion.
This is definitely something I will look into. It should not be too hard to translate it to this project.

I will make an PR if I have time to work on it.

**Comment by rmehri01** [comment]
I also agree this is a great idea, I'd be happy to help out if needed as well! :smile:

**Comment by Uaitt** [comment]
I think that the big work would be to convert the ~1300 lines of the current JSON theme into a YAML. Since I cannot write the JS code, I may help doing that 😃

**Comment by Uaitt** [comment]
Hey guys, I have started to work on this :) 

I will probably open a PR in the upcoming weeks 😃 (at least in draft, so that you guys can see the work). 
I am also trying to copy the JavaScript code from the dracula repo, but I am sure that I will need some feedback as I suck at js.

**Comment by s1e2b3i4** [comment]
The changes are now in master. Thanks again for your proposal! :+1: 
Resolved in #5
