### ISSUE TITLE
Terminal colors are not matching original theme

### ISSUE THREAD

**Issue by svipas** [s1e2b3i4/onenord-vscode#7]
`terminal.ansi*` colors should be updated to match original theme, could be picked up from this file: https://github.com/rmehri01/onenord.nvim/blob/main/extras/warp/onenord.yaml

**Comment by s1e2b3i4** [comment]
You are totally right! I committed a new version and the colors should now be fixed.

**Comment by s1e2b3i4** [comment]
The changes are live in the latest Version of the Theme (v0.4.0).
Thanks for bringing this up!

**Comment by svipas** [comment]
Thanks, there is still mismatch, I created a PR: https://github.com/s1e2b3i4/onenord-vscode/pull/11
