### ISSUE TITLE
Error view background hard to read

### ISSUE THREAD

**Issue by svipas** [s1e2b3i4/onenord-vscode#8]
Maybe it would be better to change background color of error view to editor background or another one? Same goes for foreground color since it's too white. But that's my opinion.

<img width="1621" alt="image" src="https://github.com/s1e2b3i4/onenord-vscode/assets/10441177/21eb102c-452a-43bc-88ee-7907ee9d3874">

**Comment by s1e2b3i4** [comment]
I am not exactly sure what error view do you mean. But sure, this is definitely hard to read.
Attached is a screenshot of my Problems view and the error popup. 

![image](https://github.com/s1e2b3i4/onenord-vscode/assets/28140755/a9bef224-1bb2-4d3d-bb31-e99def5c597b)

**Comment by svipas** [comment]
Yeah, I guess there's a room for improvement here to improve contrast.

**Comment by svipas** [comment]
Fixed by https://github.com/s1e2b3i4/onenord-vscode/pull/14

**Comment by s1e2b3i4** [comment]
Great finding! It was definitely difficult to read before! Thanks!
